services:
  dcrd:
    build:
      context: ./dcrd
      args:
        DCRD_VERSION: ${DCRD_VERSION:-master}
    container_name: decred-pulse-dcrd
    ports:
      - "9108:9108"  # P2P port
      - "9109:9109"  # RPC port
    volumes:
      - dcrd-data:/home/dcrd/.dcrd
      - dcrd-certs:/certs
      - ./dcrd.conf:/home/dcrd/.dcrd/dcrd.conf:ro
    environment:
      - DCRD_EXTRA_ARGS=${DCRD_EXTRA_ARGS:---txindex}
    command: >
      --rpcuser=${DCRD_RPC_USER:-decred}
      --rpcpass=${DCRD_RPC_PASS:-decredpass}
      --rpclisten=0.0.0.0:9109
      --rpccert=/certs/rpc.cert
      --rpckey=/certs/rpc.key
    restart: unless-stopped
    networks:
      - decred-network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -k -u ${DCRD_RPC_USER:-decred}:${DCRD_RPC_PASS:-decredpass} -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"1.0\",\"method\":\"getinfo\",\"params\":[],\"id\":1}' https://127.0.0.1:9109 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  dcrwallet:
    build:
      context: ./dcrwallet
      args:
        DCRWALLET_VERSION: ${DCRWALLET_VERSION:-master}
    container_name: decred-pulse-dcrwallet
    ports:
      - "9110:9110"  # RPC port
      - "9111:9111"  # gRPC port
    volumes:
      - dcrwallet-data:/home/dcrwallet/.dcrwallet
      - dcrd-certs:/certs:ro  # Read-only access to dcrd's certs
    environment:
      - DCRWALLET_RPC_USER=${DCRWALLET_RPC_USER:-dcrwallet}
      - DCRWALLET_RPC_PASS=${DCRWALLET_RPC_PASS:-dcrwalletpass}
      - DCRD_RPC_USER=${DCRD_RPC_USER:-decred}
      - DCRD_RPC_PASS=${DCRD_RPC_PASS:-decredpass}
      - DCRD_RPC_HOST=dcrd
      - DCRWALLET_GAP_LIMIT=${DCRWALLET_GAP_LIMIT:-1000}  # Address gap limit for discovery
    command: >
      --gaplimit=${DCRWALLET_GAP_LIMIT:-1000}
    depends_on:
      dcrd:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - decred-network
    healthcheck:
      test: ["CMD", "sh", "-c", "dcrctl --wallet --rpcuser=$${DCRWALLET_RPC_USER} --rpcpass=$${DCRWALLET_RPC_PASS} --rpcserver=127.0.0.1:9110 --rpccert=/certs/rpc.cert walletinfo || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  backend:
    build: ./backend
    container_name: decred-pulse-backend
    ports:
      - "8080:8080"
    volumes:
      - dcrd-certs:/certs:ro
      - dcrwallet-data:/wallet-data:ro  # Read-only access to wallet logs
    environment:
      - PORT=8080
      - DCRD_RPC_HOST=dcrd
      - DCRD_RPC_PORT=9109
      - DCRD_RPC_USER=${DCRD_RPC_USER:-decred}
      - DCRD_RPC_PASS=${DCRD_RPC_PASS:-decredpass}
      - DCRD_RPC_CERT=/certs/rpc.cert
      - DCRWALLET_RPC_HOST=dcrwallet
      - DCRWALLET_RPC_PORT=9110
      - DCRWALLET_RPC_USER=${DCRWALLET_RPC_USER:-dcrwallet}
      - DCRWALLET_RPC_PASS=${DCRWALLET_RPC_PASS:-dcrwalletpass}
      - DCRWALLET_RPC_CERT=/certs/rpc.cert
    depends_on:
      dcrd:
        condition: service_healthy
      dcrwallet:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - decred-network

  frontend:
    build: ./frontend
    container_name: decred-pulse-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - decred-network

networks:
  decred-network:
    driver: bridge

volumes:
  dcrd-data:
    driver: local
  dcrd-certs:
    driver: local
  dcrwallet-data:
    driver: local
